from __future__ import annotations

METRICS_REGISTRY: dict[str, dict[str, dict[str, str]]] = {
    "canonical_core": {
        "duration_sec": {"source": "total_timer_time", "unit": "sec"},
        "distance_m":  {"source": "total_distance",    "unit": "m"},
        "avg_hr":      {"source": "avg_heart_rate",    "unit": "bpm"},
        "max_hr":      {"source": "max_heart_rate",    "unit": "bpm"},
        "calories":    {"source": "total_calories",    "unit": "kcal"},
        "gain_m":      {"source": "total_ascent",      "unit": "m"},
        "descent_m":   {"source": "total_descent",     "unit": "m"},
        "max_alt_m":   {"source": "max_altitude",      "unit": "m"},
        "min_alt_m":   {"source": "min_altitude",      "unit": "m"},
        "avg_speed":   {"source": "avg_speed",         "unit": "m/s"},
        "avg_cadence": {"source": "avg_cadence",       "unit": "rpm"},
        "avg_power":   {"source": "avg_power",         "unit": "watts"},
    },
    "session_meta": {
        "start_time":          {"source": "start_time"},
        "start_position_lat":  {"source": "start_position_lat"},
        "start_position_long": {"source": "start_position_long"},
        "sport":               {"source": "sport"},
        "sub_sport":           {"source": "sub_sport"},
    },
    "record_fields": {
        "heart_rate": {"source": "heart_rate", "unit": "bpm"},
        "speed":      {"source": "speed",      "unit": "m/s"},
        "altitude":   {"source": "altitude",   "unit": "m"},
        "distance":   {"source": "distance",   "unit": "m"},
        "cadence":    {"source": "cadence",    "unit": "rpm"},
        "power":      {"source": "power",      "unit": "watts"},
        "temperature":{"source": "temperature", "unit": "C"},
    },
    "lap_fields": {
        "start_time":       {"source": "start_time"},
        "total_timer_time": {"source": "total_timer_time", "unit": "sec"},
        "total_distance":   {"source": "total_distance",   "unit": "m"},
        "avg_heart_rate":   {"source": "avg_heart_rate",   "unit": "bpm"},
        "max_heart_rate":   {"source": "max_heart_rate",   "unit": "bpm"},
        "avg_speed":        {"source": "avg_speed",        "unit": "m/s"},
        "avg_cadence":      {"source": "avg_cadence",      "unit": "rpm"},
        "avg_power":        {"source": "avg_power",        "unit": "watts"},
    },
}

SPORT_ALIASES: dict[str, str] = {
    "run": "running",
    "road_running": "running",
    "trail_run": "trail_running",
    "trail": "trail_running",
    "ride": "cycling",
    "bike": "cycling",
    "road_bike": "road_cycling",
    "road_biking": "road_cycling",
    "mountain_bike": "mountain_biking",
    "mtb": "mountain_biking",
    "walk": "walking",
    "hike": "hiking",
    "mountaineering": "mountaineering",
    "climb": "mountaineering",
    "drive": "driving",
    "car": "driving",
    "auto": "driving",
    "swim": "swimming",
}

SPORT_DISPLAY_NAMES: dict[str, str] = {
    "running": "Running",
    "trail_running": "Trail Running",
    "cycling": "Cycling",
    "road_cycling": "Road Cycling",
    "mountain_biking": "Mountain Biking",
    "hiking": "Hiking",
    "mountaineering": "Mountaineering",
    "walking": "Walking",
    "swimming": "Swimming",
    "driving": "Driving",
    "generic": "Generic",
    "unknown": "Unknown",
}
